name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Check code formatting with ruff
      run: uv run ruff check pharo_nc_mcp_server/ tests/

    - name: Check code format with ruff
      run: uv run ruff format --check pharo_nc_mcp_server/ tests/

    - name: Check markdown formatting  
      run: uv run mdformat --check README.md scripts/README.md || echo "Warning: markdown formatting check failed"

    - name: Run unit tests
      run: uv run pytest -m "not integration" --verbose